const coordinates=[[890,115],[1110,420],[815,690],[440,720],[80,510],[40,190],[420,70]];
const names=['CrowdSense','It’s me','반갑꼬리','Campus safety','AI subscription','Process flow','LunarLander'];
const arts=[
'<path d="M0 20H200M0 55H200M0 90H200M30 0V110M80 0V110M140 0V110M180 0V110" opacity=".25"/><circle cx="80" cy="55" r="29"/><circle cx="80" cy="55" r="17"/><path d="M80 10V100M35 55H125"/><circle cx="145" cy="24" r="6"/><circle cx="32" cy="88" r="4"/>',
'<rect x="40" y="6" width="110" height="85" rx="2"/><rect x="55" y="18" width="110" height="85" rx="2"/><circle cx="84" cy="48" r="12"/><path d="M108 39H147M108 48H135M70 76H147M70 84H126"/>',
'<path d="M22 76Q40 20 73 57T130 50T187 72" stroke-dasharray="3 5"/><path d="M89 24a20 20 0 0 1 40 0c0 18-20 40-20 40S89 42 89 24Z"/><circle cx="109" cy="24" r="6"/><ellipse cx="108" cy="85" rx="47" ry="10"/>',
'<path d="M40 80L50 26L99 7L163 39L149 88Z"/><path d="M40 80L99 57L163 39M50 26L99 57L149 88M99 7V57"/><circle cx="99" cy="57" r="14"/><circle cx="50" cy="26" r="4"/><circle cx="149" cy="88" r="4"/>',
'<path d="M20 10V94H190"/><path d="M45 90V55H63V90M83 90V36H101V90M121 90V14H139V90M159 90V25H177V90"/><path d="M26 52L79 32L128 8L186 15" stroke-dasharray="2 4"/>',
'<path d="M6 55H192"/><rect x="12" y="34" width="39" height="40"/><rect x="82" y="34" width="39" height="40"/><rect x="153" y="34" width="39" height="40"/><path d="M60 48L68 55L60 62M132 48L140 55L132 62"/><path d="M26 85H175" stroke-dasharray="4 7"/>',
'<path d="M84 38H118L123 66H78ZM88 38V23H113V38M82 63L64 85H52M118 63L134 85H147M90 69L100 88L110 69"/><path d="M15 105L43 97L70 103H140L167 91L195 101"/><circle cx="165" cy="20" r="10"/>'
];
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover:hover) and (pointer:fine)');let paused=reduced.matches,active=-1,detail=-1,time=0,last=0,lastPaint=0;const nodeRoot=document.querySelector('#nodes'),floor=document.querySelector('#floor'),dialog=document.querySelector('#project-dialog');
nodeRoot.innerHTML=projects.map((p,i)=>`<div class="node" style="left:${coordinates[i][0]}px;top:${coordinates[i][1]}px;--i:${i}" data-index="${i}"><button class="node-trigger" aria-label="${p.title} 영상 미리보기 및 상세 보기" aria-haspopup="dialog"><span class="node-base"><span class="base-status">${String(i+1).padStart(2,'0')} / ${i===0?'AWARD WINNING':'PROJECT FIELD'}</span><span class="base-art"><svg viewBox="0 0 210 110" aria-hidden="true">${arts[i]}</svg></span><span class="base-corner">+</span></span><span class="base-label"><small>${String(i+1).padStart(2,'0')}</small>${names[i]}</span><span class="beam"></span><span class="hologram"><span class="holo-top"><b>${names[i].toUpperCase()}</b><b>● MOTION STUDY</b></span><span class="hologram-screen"><canvas width="960" height="540" data-scene="${p.id}" aria-hidden="true"></canvas></span><span class="holo-bottom">ENTER THIS WORLD ↗</span></span></button></div>`).join('');
const connections=document.querySelector('.connections');connections.innerHTML=coordinates.map(([x,y],i)=>{const endX=x+123,endY=y+74,path=`M700 445 L${700+(endX-700)*.5} ${445+(endY-445)*.17} L${endX} ${endY}`;return `<path class="track" d="${path}"/><path class="pulse" style="animation-delay:-${i*1.1}s" d="${path}"/><circle cx="${endX}" cy="${endY}" r="3"/>`}).join('');
const floating=document.createElement('div');floating.id='floating-holo';floating.setAttribute('aria-hidden','true');floating.innerHTML='<div class=projection-light></div><div class=floating-face><div class=floating-label></div><canvas width=960 height=540></canvas><div class=floating-foot>PROJECT MOTION STUDY <span>CLICK TO ENTER ↗</span></div></div>';document.querySelector('#universe').append(floating);const floatingContext=floating.querySelector('canvas').getContext('2d');
const nodes=[...document.querySelectorAll('.node')],canvases=[...document.querySelectorAll('[data-scene]')].map(el=>({el,c:el.getContext('2d')}));
function activate(i){active=i;floating.classList.toggle('shown',i>=0);if(i>=0){const r=nodes[i].querySelector('.node-base').getBoundingClientRect();const w=innerWidth<700?235:365;floating.style.width=w+'px';floating.style.left=Math.max(16,Math.min(innerWidth-w-16,r.x+r.width/2-w/2))+'px';floating.style.top=Math.max(innerWidth<700?295:200,r.y-(innerWidth<700?110:155))+'px';floating.querySelector('.floating-label').textContent=names[i].toUpperCase()+' / MOTION STUDY';scenes[projects[i].id](floatingContext,time)}nodes.forEach((n,k)=>n.classList.toggle('is-active',k===i));const p=projects[i];document.querySelector('.caption-index').textContent=p?p.channel:'00 / EXPLORE THE FIELD';document.querySelector('.caption-title').textContent=p?p.title:'하나의 질문이, 하나의 세계로.';document.querySelector('.caption-help').innerHTML=p?'클릭해서 기획의 과정으로 들어가기 <b>↗</b>':(fine.matches?'패널 위에 마우스를 올려보세요':'패널을 터치하면 영상이 떠오릅니다')+' <b>↗</b>';if(i>=0)scenes[p.id](canvases[i].c,time)}
nodes.forEach((node,i)=>{const trigger=node.querySelector('button');node.addEventListener('pointerenter',()=>{if(fine.matches)activate(i)});node.addEventListener('pointerleave',()=>{if(fine.matches)activate(-1)});trigger.addEventListener('focus',()=>activate(i));trigger.addEventListener('blur',()=>{if(!dialog.open)activate(-1)});trigger.addEventListener('click',e=>{if(!fine.matches&&node.dataset.armed!=='true'){e.preventDefault();nodes.forEach(n=>delete n.dataset.armed);node.dataset.armed='true';activate(i);document.querySelector('.caption-help').textContent='한 번 더 터치하면 자세히 볼 수 있습니다';return}openProject(i)})});
function fit(){document.documentElement.style.setProperty('--world-scale',Math.min(innerWidth<700?innerWidth/1550:innerWidth/1550,(innerHeight-170)/750,1.16))}fit();addEventListener('resize',fit);
const scene=document.querySelector('#spatial-scene');let tx=0,ty=0,cx=0,cy=0;document.querySelector('#universe').addEventListener('pointermove',e=>{if(!fine.matches||paused||active>=0)return;tx=(e.clientX/innerWidth-.5)*18;ty=(e.clientY/innerHeight-.5)*10});document.querySelector('#universe').addEventListener('pointerleave',()=>{tx=ty=0});
const motion=document.querySelector('#motion');function syncMotion(){document.body.classList.toggle('paused',paused);motion.setAttribute('aria-pressed',String(paused));motion.setAttribute('aria-label',paused?'애니메이션 재생':'애니메이션 일시정지');motion.querySelector('span').textContent=paused?'MOTION OFF':'MOTION ON'}syncMotion();motion.addEventListener('click',()=>{paused=!paused;syncMotion()});reduced.addEventListener('change',e=>{paused=e.matches;syncMotion()});
const detailCanvas=document.querySelector('#detail-canvas'),detailContext=detailCanvas.getContext('2d');let previousFocus;
function populateDetail(i){detail=(i+projects.length)%projects.length;const p=projects[detail];document.querySelector('#detail-channel').textContent=p.channel;document.querySelector('#detail-status').textContent=p.status;document.querySelector('#detail-title').textContent=p.title;document.querySelector('#detail-question').textContent=p.problem;document.querySelector('#detail-description').innerHTML=p.description;document.querySelector('#detail-metric').innerHTML=`<strong>${p.metric}</strong>${p.metricText}`;document.querySelector('#detail-tags').innerHTML=p.tags.map(s=>`<span>${s}</span>`).join('');document.querySelector('#detail-link').href=`./projects/${p.id}/`;document.querySelector('#detail-count').textContent=`${String(detail+1).padStart(2,'0')} / 07`;dialog.setAttribute('aria-labelledby','detail-title');scenes[p.id](detailContext,time);dialog.scrollTop=0}
function openProject(i){previousFocus=document.activeElement;populateDetail(i);if(!dialog.open)dialog.showModal()}
document.querySelector('#prev-project').addEventListener('click',()=>populateDetail(detail-1));document.querySelector('#next-project').addEventListener('click',()=>populateDetail(detail+1));document.querySelectorAll('dialog .close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));dialog.addEventListener('close',()=>{detail=-1;previousFocus?.focus()});
const about=document.querySelector('#about-dialog');document.querySelector('#about-button').addEventListener('click',()=>about.showModal());
const indexPanel=document.querySelector('#index-panel');document.querySelector('#index-list').innerHTML=projects.map((p,i)=>`<button class="index-row" data-index="${i}" aria-haspopup="dialog"><small>0${i+1}</small><strong>${p.title}</strong><em>${p.type==='service'?'SERVICE PLANNING':'DATA & EXPERIMENT'}</em><span>↗</span></button>`).join('');document.querySelectorAll('.index-row').forEach(b=>b.addEventListener('click',()=>openProject(Number(b.dataset.index))));function setView(index){indexPanel.hidden=!index;document.querySelector('#spatial-view').classList.toggle('selected',!index);document.querySelector('#index-view').classList.toggle('selected',index);document.querySelector('#spatial-view').setAttribute('aria-pressed',String(!index));document.querySelector('#index-view').setAttribute('aria-pressed',String(index));scene.inert=index;document.querySelector('.hover-caption').hidden=index;activate(-1)}document.querySelector('#spatial-view').addEventListener('click',()=>setView(false));document.querySelector('#index-view').addEventListener('click',()=>setView(true));document.querySelector('#world-button').addEventListener('click',()=>setView(false));
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(!paused&&!document.hidden)time+=dt;if(now-lastPaint>33){if(!paused&&!document.hidden){if(detail>=0)scenes[projects[detail].id](detailContext,time);else if(active>=0&&indexPanel.hidden)scenes[projects[active].id](floatingContext,time);if(active<0){cx+=(tx-cx)*.07;cy+=(ty-cy)*.07;scene.style.setProperty('--camera-x',`${cx}px`);scene.style.setProperty('--camera-y',`${cy}px`)}}lastPaint=now}requestAnimationFrame(frame)}canvases.forEach((o,i)=>scenes[projects[i].id](o.c,0));requestAnimationFrame(frame);document.body.classList.add('world-enter');activate(-1);
